apiVersion: chaos-mesh.org/v1alpha1
kind: IoChaos
metadata:
  name: io-delay-cdc
  labels:
    app: io-delay-cdc
spec:
  action: latency
  mode: one
  selector:
    pods:
      default: # default namespace
        - cdc-0
        - cdc-1
        - cdc-2
  volumePath: /data
  path: "/data/**/*"   # todo: figure this out, maybe /data/*
  delay: "100ms"
  percent: 50
  duration: "60s"
  scheduler:
    cron: "@every 2m"
