# network partition between cdc pod
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition-cdc
  labels:
    app: network-partition-cdc
spec:
  action: partition
  mode: one
  selector:
    labelSelectors:
      "app": "cdc"
  direction: both
  target:
    selector:
      namespace:
        - playground
      labelSelectors:
        "app": "cdc"
    mode: one
  duration: '10s'
  scheduler:
    cron: '@every 40s'
