---
# network partition between DM-worker and DM-master
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition-cdc
  labels:
    app: network-partition-cdc
spec:
  action: partition
  mode: one
  selector:
    labelSelectors:
      "app": "cdc"
  direction: both
  target:
    selector:
      labelSelectors:
        "app": "cdc"
    mode: one
  duration: "30s"
  scheduler:
    cron: "2-59/3 * * * *" # At every 3rd minute from 2 through 59, (2, 5, 8, ...)
