apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-cdc
  labels:
    app: pod-failure-cdc
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    pods:
      default: # default namespace
        - cdc-0
        - cdc-1
        - cdc-2
  scheduler:
    cron: "@every 2m"
