apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-cdc
  labels:
    app: pod-kill-cdc
spec:
  action: pod-kill
  mode: one
  selector:
    pods:
      default: # default namespace
        - cdc-0
        - cdc-1
        - cdc-2
  scheduler:
    cron: "@every 1m"
