apiVersion: v1
kind: Service
metadata:
  name: cdc
  labels:
    app: cdc
spec:
  ports:
    - name: cdc
      port: 8300
      targetPort: 8300
  selector:
    app: cdc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdc
  labels:
    app: cdc
spec:
  selector:
    matchLabels:
      app: cdc
  serviceName: cdc
  replicas: 3  # 3 cdc instances
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: cdc
    spec:
      containers:
        - name: cdc
          image: cdc:chaos # build this image in GitHub action workflow
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: cdc
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8300
              name: cdc
          command:    # todo: start cdc instance
            - "/cdc"
#            - "--name=$(MY_POD_NAME)"
#            - "--worker-addr=0.0.0.0:8300"
#            - "--advertise-addr=$(MY_POD_NAME).cdc.$(MY_POD_NAMESPACE):8300"
#            - "--join=dm-master-0.dm-master.$(MY_POD_NAMESPACE):8261,dm-master-1.dm-master.$(MY_POD_NAMESPACE):8261,dm-master-2.dm-master.$(MY_POD_NAMESPACE):8261"
          readinessProbe:
            httpGet:
              port: 8300
              path: /status
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
  volumeClaimTemplates:
    - metadata:
        name: cdc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
