apiVersion: v1
kind: Service
metadata:
  name: cdc
  labels:
    app: cdc
spec:
  ports:
    - name: cdc
      port: 8300
      targetPort: 8300
  selector:
    app: cdc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdc
  labels:
    app: cdc
spec:
  selector:
    matchLabels:
      app: cdc
  serviceName: cdc
  replicas: 1
  template:
    metadata:
      labels:
        app: cdc
    spec:
      containers:
        - name: cdc
          image: cdc:latest
          imagePullPolicy: Never # build this image in GitHub action workflow, make sure use local image
          volumeMounts:
            - mountPath: /data
              name: cdc
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8300
              name: cdc
          command:
            - "/cdc"
#            - "--advertise-addr=$(MY_POD_NAME).cdc.$(MY_POD_NAMESPACE):8300"
#            - "--join=dm-master-0.dm-master.$(MY_POD_NAMESPACE):8261,dm-master-1.dm-master.$(MY_POD_NAMESPACE):8261,dm-master-2.dm-master.$(MY_POD_NAMESPACE):8261"
          readinessProbe:
            httpGet:
              port: 8300
              path: /status
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
  volumeClaimTemplates:
    - metadata:
        name: cdc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi


# apiVersion: v1
# kind: Service
# metadata:
#   name: cdc
#   labels:
#     app: cdc
# spec:
#   ports:
#     - name: cdc
#       port: 8300
#       targetPort: 8300
#   selector:
#     app: cdc
#   clusterIP: None
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: cdc
#   labels:
#     app: cdc
# spec:
#   selector:
#     matchLabels:
#       app: cdc
#   serviceName: cdc
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: cdc
#     spec:
#       containers:
#       - name: cdc
#         image: cdc:latest
#         ports:
#         - containerPort: 8300
#           name: cdc
#         volumeMounts:
#         - name: data-dir
#           mountPath: /tmp/cdc_data
#   volumeClaimTemplates:
#   - metadata:
#       name: data-dir
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       resources:
#         requests:
#           storage: 10Gi
