apiVersion: batch/v1
kind: Job
metadata:
  name: bank-workload
spec:
  template:
    spec:
      containers:
        - name: bank-workload
          image: bank-workload # build this image in GitHub action workflow
          imagePullPolicy: IfNotPresent
          command:
            - "/bank"
            - "--upstream=root@tcp(${UP_TIDB_HOST}:${UP_TIDB_PORT})/bank"
            - "--downstream=root@tcp(${DOWN_TIDB_HOST}:${DOWN_TIDB_PORT})/bank"
            - "--test-round=2000"
      restartPolicy: Never
  backoffLimit: 0 # fail immediately
