/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pingcap.simple.avro;
@org.apache.avro.specific.AvroGenerated
public enum DMLType implements org.apache.avro.generic.GenericEnumSymbol<DMLType> {
  INSERT, UPDATE, DELETE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DMLType\",\"namespace\":\"com.pingcap.simple.avro\",\"symbols\":[\"INSERT\",\"UPDATE\",\"DELETE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
