/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pingcap.simple.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class IndexSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3804685873462954838L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IndexSchema\",\"namespace\":\"com.pingcap.simple.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"unique\",\"type\":\"boolean\"},{\"name\":\"primary\",\"type\":\"boolean\"},{\"name\":\"nullable\",\"type\":\"boolean\"},{\"name\":\"columns\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}],\"docs\":\"each index's schema information\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<IndexSchema> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<IndexSchema> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<IndexSchema> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<IndexSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<IndexSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this IndexSchema to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a IndexSchema from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a IndexSchema instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static IndexSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence name;
  private boolean unique;
  private boolean primary;
  private boolean nullable;
  private java.util.List<java.lang.CharSequence> columns;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public IndexSchema() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param unique The new value for unique
   * @param primary The new value for primary
   * @param nullable The new value for nullable
   * @param columns The new value for columns
   */
  public IndexSchema(java.lang.CharSequence name, java.lang.Boolean unique, java.lang.Boolean primary, java.lang.Boolean nullable, java.util.List<java.lang.CharSequence> columns) {
    this.name = name;
    this.unique = unique;
    this.primary = primary;
    this.nullable = nullable;
    this.columns = columns;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return unique;
    case 2: return primary;
    case 3: return nullable;
    case 4: return columns;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: unique = (java.lang.Boolean)value$; break;
    case 2: primary = (java.lang.Boolean)value$; break;
    case 3: nullable = (java.lang.Boolean)value$; break;
    case 4: columns = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'unique' field.
   * @return The value of the 'unique' field.
   */
  public boolean getUnique() {
    return unique;
  }


  /**
   * Sets the value of the 'unique' field.
   * @param value the value to set.
   */
  public void setUnique(boolean value) {
    this.unique = value;
  }

  /**
   * Gets the value of the 'primary' field.
   * @return The value of the 'primary' field.
   */
  public boolean getPrimary() {
    return primary;
  }


  /**
   * Sets the value of the 'primary' field.
   * @param value the value to set.
   */
  public void setPrimary(boolean value) {
    this.primary = value;
  }

  /**
   * Gets the value of the 'nullable' field.
   * @return The value of the 'nullable' field.
   */
  public boolean getNullable() {
    return nullable;
  }


  /**
   * Sets the value of the 'nullable' field.
   * @param value the value to set.
   */
  public void setNullable(boolean value) {
    this.nullable = value;
  }

  /**
   * Gets the value of the 'columns' field.
   * @return The value of the 'columns' field.
   */
  public java.util.List<java.lang.CharSequence> getColumns() {
    return columns;
  }


  /**
   * Sets the value of the 'columns' field.
   * @param value the value to set.
   */
  public void setColumns(java.util.List<java.lang.CharSequence> value) {
    this.columns = value;
  }

  /**
   * Creates a new IndexSchema RecordBuilder.
   * @return A new IndexSchema RecordBuilder
   */
  public static com.pingcap.simple.avro.IndexSchema.Builder newBuilder() {
    return new com.pingcap.simple.avro.IndexSchema.Builder();
  }

  /**
   * Creates a new IndexSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new IndexSchema RecordBuilder
   */
  public static com.pingcap.simple.avro.IndexSchema.Builder newBuilder(com.pingcap.simple.avro.IndexSchema.Builder other) {
    if (other == null) {
      return new com.pingcap.simple.avro.IndexSchema.Builder();
    } else {
      return new com.pingcap.simple.avro.IndexSchema.Builder(other);
    }
  }

  /**
   * Creates a new IndexSchema RecordBuilder by copying an existing IndexSchema instance.
   * @param other The existing instance to copy.
   * @return A new IndexSchema RecordBuilder
   */
  public static com.pingcap.simple.avro.IndexSchema.Builder newBuilder(com.pingcap.simple.avro.IndexSchema other) {
    if (other == null) {
      return new com.pingcap.simple.avro.IndexSchema.Builder();
    } else {
      return new com.pingcap.simple.avro.IndexSchema.Builder(other);
    }
  }

  /**
   * RecordBuilder for IndexSchema instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IndexSchema>
    implements org.apache.avro.data.RecordBuilder<IndexSchema> {

    private java.lang.CharSequence name;
    private boolean unique;
    private boolean primary;
    private boolean nullable;
    private java.util.List<java.lang.CharSequence> columns;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pingcap.simple.avro.IndexSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.unique)) {
        this.unique = data().deepCopy(fields()[1].schema(), other.unique);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.primary)) {
        this.primary = data().deepCopy(fields()[2].schema(), other.primary);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.nullable)) {
        this.nullable = data().deepCopy(fields()[3].schema(), other.nullable);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.columns)) {
        this.columns = data().deepCopy(fields()[4].schema(), other.columns);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing IndexSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pingcap.simple.avro.IndexSchema other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.unique)) {
        this.unique = data().deepCopy(fields()[1].schema(), other.unique);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.primary)) {
        this.primary = data().deepCopy(fields()[2].schema(), other.primary);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.nullable)) {
        this.nullable = data().deepCopy(fields()[3].schema(), other.nullable);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.columns)) {
        this.columns = data().deepCopy(fields()[4].schema(), other.columns);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.pingcap.simple.avro.IndexSchema.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.pingcap.simple.avro.IndexSchema.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'unique' field.
      * @return The value.
      */
    public boolean getUnique() {
      return unique;
    }


    /**
      * Sets the value of the 'unique' field.
      * @param value The value of 'unique'.
      * @return This builder.
      */
    public com.pingcap.simple.avro.IndexSchema.Builder setUnique(boolean value) {
      validate(fields()[1], value);
      this.unique = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'unique' field has been set.
      * @return True if the 'unique' field has been set, false otherwise.
      */
    public boolean hasUnique() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'unique' field.
      * @return This builder.
      */
    public com.pingcap.simple.avro.IndexSchema.Builder clearUnique() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'primary' field.
      * @return The value.
      */
    public boolean getPrimary() {
      return primary;
    }


    /**
      * Sets the value of the 'primary' field.
      * @param value The value of 'primary'.
      * @return This builder.
      */
    public com.pingcap.simple.avro.IndexSchema.Builder setPrimary(boolean value) {
      validate(fields()[2], value);
      this.primary = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'primary' field has been set.
      * @return True if the 'primary' field has been set, false otherwise.
      */
    public boolean hasPrimary() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'primary' field.
      * @return This builder.
      */
    public com.pingcap.simple.avro.IndexSchema.Builder clearPrimary() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'nullable' field.
      * @return The value.
      */
    public boolean getNullable() {
      return nullable;
    }


    /**
      * Sets the value of the 'nullable' field.
      * @param value The value of 'nullable'.
      * @return This builder.
      */
    public com.pingcap.simple.avro.IndexSchema.Builder setNullable(boolean value) {
      validate(fields()[3], value);
      this.nullable = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'nullable' field has been set.
      * @return True if the 'nullable' field has been set, false otherwise.
      */
    public boolean hasNullable() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'nullable' field.
      * @return This builder.
      */
    public com.pingcap.simple.avro.IndexSchema.Builder clearNullable() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'columns' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getColumns() {
      return columns;
    }


    /**
      * Sets the value of the 'columns' field.
      * @param value The value of 'columns'.
      * @return This builder.
      */
    public com.pingcap.simple.avro.IndexSchema.Builder setColumns(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[4], value);
      this.columns = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'columns' field has been set.
      * @return True if the 'columns' field has been set, false otherwise.
      */
    public boolean hasColumns() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'columns' field.
      * @return This builder.
      */
    public com.pingcap.simple.avro.IndexSchema.Builder clearColumns() {
      columns = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public IndexSchema build() {
      try {
        IndexSchema record = new IndexSchema();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.unique = fieldSetFlags()[1] ? this.unique : (java.lang.Boolean) defaultValue(fields()[1]);
        record.primary = fieldSetFlags()[2] ? this.primary : (java.lang.Boolean) defaultValue(fields()[2]);
        record.nullable = fieldSetFlags()[3] ? this.nullable : (java.lang.Boolean) defaultValue(fields()[3]);
        record.columns = fieldSetFlags()[4] ? this.columns : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<IndexSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<IndexSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<IndexSchema>
    READER$ = (org.apache.avro.io.DatumReader<IndexSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeBoolean(this.unique);

    out.writeBoolean(this.primary);

    out.writeBoolean(this.nullable);

    long size0 = this.columns.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.columns) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.unique = in.readBoolean();

      this.primary = in.readBoolean();

      this.nullable = in.readBoolean();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.columns;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("columns").schema());
        this.columns = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.unique = in.readBoolean();
          break;

        case 2:
          this.primary = in.readBoolean();
          break;

        case 3:
          this.nullable = in.readBoolean();
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.columns;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("columns").schema());
            this.columns = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










