/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pingcap.simple.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Watermark extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4556221810637242235L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Watermark\",\"namespace\":\"com.pingcap.simple.avro\",\"fields\":[{\"name\":\"version\",\"type\":\"int\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"commitTs\",\"type\":\"long\"},{\"name\":\"buildTs\",\"type\":\"long\"}],\"docs\":\"the message format of the watermark event\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Watermark> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Watermark> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Watermark> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Watermark> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Watermark> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Watermark to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Watermark from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Watermark instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Watermark fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int version;
  private java.lang.CharSequence type;
  private long commitTs;
  private long buildTs;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Watermark() {}

  /**
   * All-args constructor.
   * @param version The new value for version
   * @param type The new value for type
   * @param commitTs The new value for commitTs
   * @param buildTs The new value for buildTs
   */
  public Watermark(java.lang.Integer version, java.lang.CharSequence type, java.lang.Long commitTs, java.lang.Long buildTs) {
    this.version = version;
    this.type = type;
    this.commitTs = commitTs;
    this.buildTs = buildTs;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return version;
    case 1: return type;
    case 2: return commitTs;
    case 3: return buildTs;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: version = (java.lang.Integer)value$; break;
    case 1: type = (java.lang.CharSequence)value$; break;
    case 2: commitTs = (java.lang.Long)value$; break;
    case 3: buildTs = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public int getVersion() {
    return version;
  }


  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(int value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'commitTs' field.
   * @return The value of the 'commitTs' field.
   */
  public long getCommitTs() {
    return commitTs;
  }


  /**
   * Sets the value of the 'commitTs' field.
   * @param value the value to set.
   */
  public void setCommitTs(long value) {
    this.commitTs = value;
  }

  /**
   * Gets the value of the 'buildTs' field.
   * @return The value of the 'buildTs' field.
   */
  public long getBuildTs() {
    return buildTs;
  }


  /**
   * Sets the value of the 'buildTs' field.
   * @param value the value to set.
   */
  public void setBuildTs(long value) {
    this.buildTs = value;
  }

  /**
   * Creates a new Watermark RecordBuilder.
   * @return A new Watermark RecordBuilder
   */
  public static com.pingcap.simple.avro.Watermark.Builder newBuilder() {
    return new com.pingcap.simple.avro.Watermark.Builder();
  }

  /**
   * Creates a new Watermark RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Watermark RecordBuilder
   */
  public static com.pingcap.simple.avro.Watermark.Builder newBuilder(com.pingcap.simple.avro.Watermark.Builder other) {
    if (other == null) {
      return new com.pingcap.simple.avro.Watermark.Builder();
    } else {
      return new com.pingcap.simple.avro.Watermark.Builder(other);
    }
  }

  /**
   * Creates a new Watermark RecordBuilder by copying an existing Watermark instance.
   * @param other The existing instance to copy.
   * @return A new Watermark RecordBuilder
   */
  public static com.pingcap.simple.avro.Watermark.Builder newBuilder(com.pingcap.simple.avro.Watermark other) {
    if (other == null) {
      return new com.pingcap.simple.avro.Watermark.Builder();
    } else {
      return new com.pingcap.simple.avro.Watermark.Builder(other);
    }
  }

  /**
   * RecordBuilder for Watermark instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Watermark>
    implements org.apache.avro.data.RecordBuilder<Watermark> {

    private int version;
    private java.lang.CharSequence type;
    private long commitTs;
    private long buildTs;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pingcap.simple.avro.Watermark.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.version)) {
        this.version = data().deepCopy(fields()[0].schema(), other.version);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.commitTs)) {
        this.commitTs = data().deepCopy(fields()[2].schema(), other.commitTs);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.buildTs)) {
        this.buildTs = data().deepCopy(fields()[3].schema(), other.buildTs);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Watermark instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pingcap.simple.avro.Watermark other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.version)) {
        this.version = data().deepCopy(fields()[0].schema(), other.version);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.commitTs)) {
        this.commitTs = data().deepCopy(fields()[2].schema(), other.commitTs);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.buildTs)) {
        this.buildTs = data().deepCopy(fields()[3].schema(), other.buildTs);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public int getVersion() {
      return version;
    }


    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public com.pingcap.simple.avro.Watermark.Builder setVersion(int value) {
      validate(fields()[0], value);
      this.version = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public com.pingcap.simple.avro.Watermark.Builder clearVersion() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.pingcap.simple.avro.Watermark.Builder setType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.pingcap.simple.avro.Watermark.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'commitTs' field.
      * @return The value.
      */
    public long getCommitTs() {
      return commitTs;
    }


    /**
      * Sets the value of the 'commitTs' field.
      * @param value The value of 'commitTs'.
      * @return This builder.
      */
    public com.pingcap.simple.avro.Watermark.Builder setCommitTs(long value) {
      validate(fields()[2], value);
      this.commitTs = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'commitTs' field has been set.
      * @return True if the 'commitTs' field has been set, false otherwise.
      */
    public boolean hasCommitTs() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'commitTs' field.
      * @return This builder.
      */
    public com.pingcap.simple.avro.Watermark.Builder clearCommitTs() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'buildTs' field.
      * @return The value.
      */
    public long getBuildTs() {
      return buildTs;
    }


    /**
      * Sets the value of the 'buildTs' field.
      * @param value The value of 'buildTs'.
      * @return This builder.
      */
    public com.pingcap.simple.avro.Watermark.Builder setBuildTs(long value) {
      validate(fields()[3], value);
      this.buildTs = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'buildTs' field has been set.
      * @return True if the 'buildTs' field has been set, false otherwise.
      */
    public boolean hasBuildTs() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'buildTs' field.
      * @return This builder.
      */
    public com.pingcap.simple.avro.Watermark.Builder clearBuildTs() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Watermark build() {
      try {
        Watermark record = new Watermark();
        record.version = fieldSetFlags()[0] ? this.version : (java.lang.Integer) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.commitTs = fieldSetFlags()[2] ? this.commitTs : (java.lang.Long) defaultValue(fields()[2]);
        record.buildTs = fieldSetFlags()[3] ? this.buildTs : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Watermark>
    WRITER$ = (org.apache.avro.io.DatumWriter<Watermark>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Watermark>
    READER$ = (org.apache.avro.io.DatumReader<Watermark>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.version);

    out.writeString(this.type);

    out.writeLong(this.commitTs);

    out.writeLong(this.buildTs);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.version = in.readInt();

      this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);

      this.commitTs = in.readLong();

      this.buildTs = in.readLong();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.version = in.readInt();
          break;

        case 1:
          this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
          break;

        case 2:
          this.commitTs = in.readLong();
          break;

        case 3:
          this.buildTs = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










