name: Check & Build

on:
  push:
    branches:
      - master
      - 'release-[0-9].[0-9]*'
  pull_request:
    branches:
      - master
      - 'release-[0-9].[0-9]*'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          # https://github.com/marketplace/actions/skip-duplicate-actions
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md"]'
          cancel_others: 'true'
          do_not_skip: '["workflow_dispatch", "schedule"]' # only skip pull_request

  docker_build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Docker Build
    runs-on: ubuntu-latest

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: docker build .

  make_check_build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Make Check & Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.4'

    - name: Cache Lint Tools
      id: cache-lint-tools
      uses: actions/cache@v2
      with:
        path: tools/bin
        key: ${{ runner.os }}-cdc-lint-tools-${{ hashFiles('tools/check/go.sum') }}

    - name: Check
      run: make check

    - name: Build
      run: make build

  lint:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.30
          args: --timeout 10m0s

      - name: Revive Lint
        uses: morphy2k/revive-action@v1
        with:
          config: tools/check/revive.toml
