name: integration-tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  pre_job:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          # https://github.com/marketplace/actions/skip-duplicate-actions
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md"]'
          cancel_others: 'true'
          do_not_skip: '["workflow_dispatch", "schedule"]' # only skip pull_request


  MySQL-integration:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: MySQL Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        run: |
         sudo rm -rf /usr/local/lib/android
         sudo rm -rf /usr/share/dotnet
         docker volume prune -f
         docker image prune -f
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-cdc-integration-vendor-${{ hashFiles('go.sum') }}

      - name: Update Vendor
        run: go mod vendor

      - name: Pull images
        run: docker-compose -f docker-compose-avro.yml pull --ignore-pull-failures

      - name: TiKV version
        run: docker run pingcap/tikv:release-4.0-nightly -V

      - name: Build Integration Framework
        run: |
          cd $GITHUB_WORKSPACE/integration
          go build

      - name: Run Integration Framework
        timeout-minutes: 45
        run: |
          cd $GITHUB_WORKSPACE/integration
          ./integration -protocol=mysql

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: ${{ github.workspace }}/docker/logs/*

      - name: Clean Up
        if: ${{ always() }}
        run: |
          $GITHUB_WORKSPACE/scripts/avro-local-test.sh down

  OldValue-integration:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: OldValue Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        run: |
         sudo rm -rf /usr/local/lib/android
         sudo rm -rf /usr/share/dotnet
         docker volume prune -f
         docker image prune -f
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-cdc-integration-vendor-${{ hashFiles('go.sum') }}

      - name: Update Vendor
        run: go mod vendor

      - name: Pull images
        run: docker-compose -f docker-compose-avro.yml pull --ignore-pull-failures

      - name: TiKV version
        run: docker run pingcap/tikv:release-4.0-nightly -V

      - name: Build Integration Framework
        run: |
          cd $GITHUB_WORKSPACE/integration
          go build

      - name: Run Integration Framework
        timeout-minutes: 45
        run: |
          cd $GITHUB_WORKSPACE/integration
          ./integration -protocol=simple-mysql-checking-old-value

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: ${{ github.workspace }}/docker/logs/*

      - name: Clean Up
        if: ${{ always() }}
        run: |
          $GITHUB_WORKSPACE/scripts/avro-local-test.sh down

  CanalJson-integration:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: CanalJson Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        run: |
         sudo rm -rf /usr/local/lib/android
         sudo rm -rf /usr/share/dotnet
         docker volume prune -f
         docker image prune -f
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-cdc-integration-vendor-${{ hashFiles('go.sum') }}

      - name: Update Vendor
        run: go mod vendor

      - name: Pull images
        run: docker-compose -f docker-compose-canal.yml pull --ignore-pull-failures

      - name: TiKV version
        run: docker run pingcap/tikv:release-4.0-nightly -V

      - name: Build Integration Framework
        run: |
          cd $GITHUB_WORKSPACE/integration
          go build

      - name: Run Integration Framework
        timeout-minutes: 45
        run: |
          cd $GITHUB_WORKSPACE/integration
          ./integration -protocol=canalJson

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: ${{ github.workspace }}/docker/logs/*

      - name: Clean Up
        if: ${{ always() }}
        run: |
          $GITHUB_WORKSPACE/scripts/canal/canal-local-test.sh down


  Canal-integration:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Canal Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        run: |
         sudo rm -rf /usr/local/lib/android
         sudo rm -rf /usr/share/dotnet
         docker volume prune -f
         docker image prune -f
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-cdc-integration-vendor-${{ hashFiles('go.sum') }}

      - name: Update Vendor
        run: go mod vendor

      - name: Pull images
        run: docker-compose -f docker-compose-canal.yml pull --ignore-pull-failures

      - name: TiKV version
        run: docker run pingcap/tikv:release-4.0-nightly -V

      - name: Build Integration Framework
        run: |
          cd $GITHUB_WORKSPACE/integration
          go build

      - name: Run Integration Framework
        timeout-minutes: 45
        run: |
          cd $GITHUB_WORKSPACE/integration
          ./integration -protocol=canal

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: ${{ github.workspace }}/docker/logs/*

      - name: Clean Up
        if: ${{ always() }}
        run: |
          $GITHUB_WORKSPACE/scripts/canal/canal-local-test.sh down

  Avro-integration:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Avro Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        run: |
         sudo rm -rf /usr/local/lib/android
         sudo rm -rf /usr/share/dotnet
         docker volume prune -f
         docker image prune -f
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-cdc-integration-vendor-${{ hashFiles('go.sum') }}

      - name: Update Vendor
        run: go mod vendor

      - name: Pull images
        run: docker-compose -f docker-compose-avro.yml pull --ignore-pull-failures

      - name: TiKV version
        run: docker run pingcap/tikv:release-4.0-nightly -V

      - name: Build Integration Framework
        run: |
          cd $GITHUB_WORKSPACE/integration
          go build

      - name: Run Integration Framework
        timeout-minutes: 45
        run: |
          cd $GITHUB_WORKSPACE/integration
          ./integration

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: ${{ github.workspace }}/docker/logs/*

      - name: Clean Up
        if: ${{ always() }}
        run: |
          $GITHUB_WORKSPACE/scripts/avro-local-test.sh down
